<a href="https://colab.research.google.com/github/444vj/child-malnutrition-01/blob/main/preprocessed_data_dhs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Define the features to keep
features_to_keep = [
    "v130", "v024", "v116", "v113", "v025", "v701", "v705", "v717", "s370b",
    "s116", "v190a", "b4", "v151", "hidx", "v218", "m5", "s301", "v212", "v445",
    "v437", "v438","hw2","hw3"]

# Read the CSV file into a pandas DataFrame
df = pd.read_csv("/content/sampled_data_850_new.csv")

# Drop all features except the ones specified in features_to_keep
dropped_features = list(set(df.columns) - set(features_to_keep))
df.drop(dropped_features, axis=1, inplace=True)

# Save the modified DataFrame to a new CSV file
df.to_csv("/content/reduced_features_new.csv", index=False)

# Print the DataFrame with dropped features (optional)
print(df)


     v113    hw2  s116  v212  v190a    v445    v438  v116  v218  v151  ...  \
0    14.0   96.0   2.0  18.0    1.0  1994.0  1452.0  31.0   2.0   1.0  ...   
1    12.0  126.0   2.0  28.0    1.0  2282.0  1623.0  13.0   3.0   1.0  ...   
2    11.0   52.0   3.0  20.0    5.0  2087.0  1529.0  12.0   3.0   1.0  ...   
3    21.0   65.0   3.0  18.0    2.0  2445.0  1462.0  41.0   2.0   1.0  ...   
4    21.0   50.0   3.0  21.0    3.0  2111.0  1489.0  12.0   2.0   1.0  ...   
..    ...    ...   ...   ...    ...     ...     ...   ...   ...   ...  ...   
594  11.0  133.0   3.0  33.0    2.0  1973.0  1568.0  13.0   1.0   1.0  ...   
595  14.0  113.0   2.0  17.0    1.0  2245.0  1556.0  13.0   3.0   1.0  ...   
596  21.0   87.0   4.0  20.0    2.0  1828.0  1454.0  12.0   3.0   1.0  ...   
597  71.0  105.0   2.0  18.0    2.0  1707.0  1489.0  13.0   2.0   1.0  ...   
598   NaN    NaN   NaN   NaN    NaN     NaN     NaN   NaN   NaN   NaN  ...   

      b4    hw3  s301  s370b   v437  v024  hidx  v025  v130    

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("/content/reduced_features_new.csv")
df

v113    hw2  s116  v212  v190a    v445    v438  v116  v218  v151  ...  \
0    14.0   96.0   2.0  18.0    1.0  1994.0  1452.0  31.0   2.0   1.0  ...   
1    12.0  126.0   2.0  28.0    1.0  2282.0  1623.0  13.0   3.0   1.0  ...   
2    11.0   52.0   3.0  20.0    5.0  2087.0  1529.0  12.0   3.0   1.0  ...   
3    21.0   65.0   3.0  18.0    2.0  2445.0  1462.0  41.0   2.0   1.0  ...   
4    21.0   50.0   3.0  21.0    3.0  2111.0  1489.0  12.0   2.0   1.0  ...   
..    ...    ...   ...   ...    ...     ...     ...   ...   ...   ...  ...   
594  11.0  133.0   3.0  33.0    2.0  1973.0  1568.0  13.0   1.0   1.0  ...   
595  14.0  113.0   2.0  17.0    1.0  2245.0  1556.0  13.0   3.0   1.0  ...   
596  21.0   87.0   4.0  20.0    2.0  1828.0  1454.0  12.0   3.0   1.0  ...   
597  71.0  105.0   2.0  18.0    2.0  1707.0  1489.0  13.0   2.0   1.0  ...   
598   NaN    NaN   NaN   NaN    NaN     NaN     NaN   NaN   NaN   NaN  ...   

      b4    hw3  s301  s370b   v437  v024  hidx  v025  v130    m5  
0    1.0  802.0   1.0    0.0  421.0  22.0   1.0   2.0   1.0  19.0  
1    1.0  778.0   1.0    0.0  601.0  13.0   3.0   2.0   3.0   NaN  
2    2.0  608.0   1.0    NaN  488.0  23.0   1.0   1.0   1.0   4.0  
3    2.0  704.0   1.0    NaN  523.0   9.0   1.0   2.0   1.0   8.0  
4    1.0  558.0   1.0    0.0  468.0  10.0   1.0   1.0   2.0   2.0  
..   ...    ...   ...    ...    ...   ...   ...   ...   ...   ...  
594  1.0  928.0   1.0    0.0  485.0  24.0   NaN   1.0   1.0  45.0  
595  2.0  832.0   1.0    0.0  544.0   8.0   2.0   2.0   1.0   NaN  
596  2.0  796.0   1.0    0.0  387.0  21.0   2.0   2.0   3.0   NaN  
597  1.0  833.0   1.0    NaN  379.0  25.0   NaN   2.0   1.0   NaN  
598  NaN    NaN   NaN    NaN    NaN   NaN   NaN   NaN   NaN   NaN  

[599 rows x 23 columns]

In [4]:
df.isnull().sum()

v113       1
hw2       41
s116      23
v212       1
v190a      1
v445      16
v438       2
v116       1
v218       1
v151       1
v717     508
v701     508
v705     508
b4         1
hw3       41
s301       1
s370b    169
v437       2
v024       1
hidx     235
v025       1
v130       1
m5       123
dtype: int64

In [5]:
df.isna().sum()

v113       1
hw2       41
s116      23
v212       1
v190a      1
v445      16
v438       2
v116       1
v218       1
v151       1
v717     508
v701     508
v705     508
b4         1
hw3       41
s301       1
s370b    169
v437       2
v024       1
hidx     235
v025       1
v130       1
m5       123
dtype: int64

In [6]:
df = df.dropna()


In [7]:
df

v113     hw2  s116  v212  v190a    v445    v438  v116  v218  v151  ...  \
4    21.0    50.0   3.0  21.0    3.0  2111.0  1489.0  12.0   2.0   1.0  ...   
19   12.0    51.0   1.0  30.0    5.0  2160.0  1556.0  11.0   1.0   2.0  ...   
27   11.0    84.0   3.0  20.0    4.0  1999.0  1552.0  12.0   2.0   1.0  ...   
47   21.0    37.0   3.0  27.0    5.0  2584.0  1520.0  12.0   1.0   1.0  ...   
76   21.0    89.0   1.0  20.0    2.0  1657.0  1444.0  12.0   2.0   1.0  ...   
77   21.0   114.0   1.0  20.0    1.0  2003.0  1522.0  31.0   6.0   2.0  ...   
80   21.0   140.0   3.0  32.0    5.0  2086.0  1524.0  12.0   1.0   1.0  ...   
98   14.0  9994.0   3.0  20.0    1.0  2622.0  1578.0  22.0   5.0   1.0  ...   
140  21.0    79.0   3.0  19.0    2.0  1728.0  1505.0  31.0   1.0   1.0  ...   
158  12.0   144.0   3.0  20.0    1.0  2177.0  1645.0  13.0   6.0   1.0  ...   
159  11.0   101.0   3.0  19.0    3.0  2164.0  1497.0  12.0   4.0   1.0  ...   
178  14.0   107.0   4.0  20.0    2.0  1767.0  1677.0  11.0   2.0   1.0  ...   
183  12.0    89.0   4.0  23.0    2.0  2752.0  1573.0  12.0   3.0   1.0  ...   
200  21.0    45.0   2.0  19.0    1.0  1849.0  1574.0  31.0   1.0   1.0  ...   
225  21.0    92.0   1.0  21.0    2.0  2214.0  1311.0  23.0   1.0   1.0  ...   
237  71.0   153.0   4.0  21.0    4.0  2343.0  1578.0  11.0   2.0   1.0  ...   
244  21.0    73.0   1.0  21.0    2.0  1685.0  1476.0  23.0   1.0   1.0  ...   
254  31.0   114.0   3.0  25.0    1.0  2479.0  1573.0  31.0   2.0   1.0  ...   
258  32.0   148.0   3.0  24.0    3.0  2300.0  1586.0  23.0   4.0   1.0  ...   
275  12.0    81.0   4.0  19.0    4.0  1838.0  1465.0  13.0   3.0   1.0  ...   
277  14.0    88.0   2.0  17.0    2.0  2097.0  1538.0  31.0   3.0   1.0  ...   
314  92.0   104.0   2.0  18.0    3.0  2006.0  1475.0  12.0   2.0   1.0  ...   
316  14.0   118.0   3.0  19.0    1.0  1978.0  1609.0  41.0   2.0   1.0  ...   
345  21.0    88.0   2.0  22.0    2.0  2164.0  1520.0  41.0   2.0   1.0  ...   
355  11.0    91.0   4.0  18.0    1.0  2161.0  1594.0  22.0   4.0   1.0  ...   
425  21.0    62.0   1.0  21.0    4.0  1969.0  1392.0  41.0   2.0   2.0  ...   
426  21.0    92.0   3.0  20.0    3.0  2203.0  1489.0  15.0   4.0   2.0  ...   
431  21.0   106.0   1.0  23.0    2.0  1835.0  1513.0  31.0   1.0   2.0  ...   
502  12.0    61.0   3.0  18.0    4.0  1809.0  1511.0  13.0   2.0   1.0  ...   
519  32.0    81.0   1.0  22.0    4.0  1911.0  1453.0  12.0   1.0   1.0  ...   
537  14.0   120.0   2.0  22.0    2.0  2496.0  1510.0  12.0   2.0   1.0  ...   

      b4     hw3  s301  s370b   v437  v024  hidx  v025  v130    m5  
4    1.0   558.0   1.0    0.0  468.0  10.0   1.0   1.0   2.0   2.0  
19   1.0   583.0   1.0    0.0  523.0   8.0   1.0   1.0   1.0   3.0  
27   2.0   741.0   1.0    0.0  482.0   5.0   1.0   2.0   1.0   8.0  
47   2.0   542.0   1.0    0.0  597.0  21.0   1.0   2.0   1.0   2.0  
76   1.0   702.0   1.0    0.0  346.0  10.0   1.0   2.0   1.0  10.0  
77   1.0   867.0   1.0    0.0  464.0  10.0   1.0   2.0   1.0  18.0  
80   2.0   875.0   1.0    0.0  485.0  16.0   1.0   2.0   1.0  32.0  
98   2.0  9994.0   1.0    0.0  653.0  20.0   1.0   2.0   2.0  16.0  
140  1.0   752.0   1.0    0.0  392.0  10.0   1.0   2.0   1.0   8.0  
158  2.0   814.0   1.0    0.0  589.0   1.0   2.0   2.0   2.0  94.0  
159  1.0   871.0   1.0    0.0  485.0  24.0   1.0   2.0   1.0  12.0  
178  2.0   721.0   1.0    0.0  497.0  29.0   1.0   1.0   1.0  18.0  
183  2.0   784.0   1.0    0.0  681.0   1.0   1.0   2.0   2.0  20.0  
200  2.0   638.0   1.0    0.0  458.0   9.0   1.0   2.0   1.0   6.0  
225  1.0   868.0   1.0    0.0  381.0  18.0   1.0   2.0   1.0  29.0  
237  1.0   863.0   1.0    0.0  584.0  33.0   1.0   1.0   1.0  23.0  
244  2.0   686.0   1.0    0.0  367.0  18.0   1.0   2.0   1.0  11.0  
254  1.0   852.0   1.0    0.0  614.0  24.0   1.0   2.0   1.0  21.0  
258  2.0   847.0   1.0    0.0  579.0   9.0   1.0   2.0   1.0  32.0  
275  2.0   676.0   1.0    0.0  395.0   8.0   1.0   2.0   1.0  12.0  
277  1.0   748.0   1.0    0

Variables

father's education v701

In [8]:
print(df['v701'].unique())

[2. 3. 0. 1.]


In [9]:

print(df['v701'].unique())
print(f'shape of original df = {df.shape}')
df["v701"]=df["v701"].replace({9:8, 0:'No education', 1:'Primary education', 2:'Secondary education', 3:'Higher education'})
indexNames = df[df['v701'] == 8].index
df.drop(indexNames , inplace=True)
print(df['v701'].unique())
print(f'shape of original df = {df.shape}')

[2. 3. 0. 1.]
shape of original df = (31, 23)
['Secondary education' 'Higher education' 'No education'
 'Primary education']
shape of original df = (31, 23)


<ipython-input-9-b516be1d3f76>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["v701"]=df["v701"].replace({9:8, 0:'No education', 1:'Primary education', 2:'Secondary education', 3:'Higher education'})
<ipython-input-9-b516be1d3f76>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(indexNames , inplace=True)


In [10]:
df['v701'].value_counts()

v701
Secondary education    18
Primary education       6
No education            4
Higher education        3
Name: count, dtype: int64

In [11]:
df = df.rename(columns={"v701": "Father's Education"})

father's occupation v705

In [12]:
print(df['v705'].unique())
df['v705']=df['v705'].replace({0:'unemployed',1:'professional',2:'clerical',3:'sales',4:'self employed',5:'Rgri',6:'household',7:'services' ,8:'skilled labour', 99.0:'dont know', 98.0:'dont know'})



[4. 5. 7. 6. 1. 9.]


In [13]:
# First, print unique values to see the context
print(df['v705'].unique())

# Update the replacement dictionary to include 9
replacement_dict = {
    0: 'unemployed',
    1: 'professional',
    2: 'clerical',
    3: 'sales',
    4: 'self employed',
    5: 'Rgri',
    6: 'household',
    7: 'services',
    8: 'skilled labour',
    9: 'other',  # Assuming 9 represents 'other'
    99.0: 'dont know',
    98.0: 'dont know'
}

# Use .loc to avoid the SettingWithCopyWarning
df.loc[:, 'v705'] = df['v705'].replace(replacement_dict)

# Drop rows where v705 is 'dont know'
df = df[df['v705'] != 'dont know']

# Print unique values and shape to verify the changes
print(df['v705'].unique())
print(f'shape of df after drop = {df.shape}')

# Print the value counts to check the distribution
print(df['v705'].value_counts())


['self employed' 'Rgri' 'services' 'household' 'professional' 9.0]
['self employed' 'Rgri' 'services' 'household' 'professional' 'other']
shape of df after drop = (31, 23)
v705
household        11
services          8
self employed     6
other             3
Rgri              2
professional      1
Name: count, dtype: int64


In [14]:
df = df.rename(columns={"v705": "Father's Occupation"})

mothers occupation v717

In [15]:
# First, print unique values to see the context
print(df['v717'].unique())

# Update the replacement dictionary to include 9
replacement_dict = {
    0: 'unemployed',
    1: 'professional',
    2: 'clerical',
    3: 'sales',
    4: 'self employed',
    5: 'Rgri',
    6: 'household',
    7: 'services',
    8: 'skilled labour',
    9: 'other',  # Assuming 9 represents 'other'
    99.0: 'dont know',
    98.0: 'dont know'
}

# Use .loc to avoid the SettingWithCopyWarning
df.loc[:, 'v717'] = df['v717'].replace(replacement_dict)

# Drop rows where v705 is 'dont know'
df = df[df['v717'] != 'dont know']

# Print unique values and shape to verify the changes
print(df['v717'].unique())
print(f'shape of df after drop = {df.shape}')

# Print the value counts to check the distribution
print(df['v717'].value_counts())


[0. 6. 4. 1. 9.]
['unemployed' 'household' 'self employed' 'professional' 'other']
shape of df after drop = (31, 23)
v717
unemployed       21
household         6
professional      2
self employed     1
other             1
Name: count, dtype: int64


In [16]:
df = df.rename(columns={"v717": "Mother's Occupation"})

area v025

In [17]:

print(df['v025'].unique())
df['v025'] = df['v025'].replace({1:'Urban', 2:'Rural'})
print(df['v025'].unique())
print(df['v025'].value_counts())


[1. 2.]
['Urban' 'Rural']
v025
Rural    25
Urban     6
Name: count, dtype: int64


In [18]:
df = df.rename(columns={"v025": "Area"})


religion v130

In [19]:
print(df['v130'].unique())
df['v130']=df['v130'].replace({1:'Hindu',2:'Muslim',3:'Christian',4:'Sikh',5:'Others',6:'Others',10:'Others' ,9:'Others', 99:'Others', 96:'Others'})


[2. 1. 3.]


In [20]:
print(df['v130'].unique())
print(f'v130 = {df.shape}')


['Muslim' 'Hindu' 'Christian']
v130 = (31, 23)


In [21]:
df['v130'].value_counts()

v130
Hindu        25
Muslim        5
Christian     1
Name: count, dtype: int64

In [22]:

df = df.rename(columns={"v130": "Religion"})

caste s116

In [23]:


df['s116'].unique()

array([3., 1., 4., 2.])

In [24]:
print(df['s116'].unique())
print(f'shape of original df = {df.shape}')
df["s116"]=df["s116"].replace({8.0:9})
indexNames = df[df['s116'] == 9].index
df.drop(indexNames , inplace=True)
print(df['s116'].unique())
print(f'shape of new df = {df.shape}')

[3. 1. 4. 2.]
shape of original df = (31, 23)
[3. 1. 4. 2.]
shape of new df = (31, 23)


In [25]:


df['s116']=df['s116'].replace({1:'SC',2:'ST',3:'OBC',4:'Others'})

In [26]:

df['s116'].value_counts()

s116
OBC       13
SC         8
Others     5
ST         5
Name: count, dtype: int64

In [27]:
df = df.rename(columns={"s116": "Caste"})

source of drinking water v113

In [28]:
df['v113'].unique()

array([21., 12., 11., 14., 71., 31., 32., 92.])

In [29]:


df = df.rename(columns={"v113": "Source of drinking water"})

In [30]:
# Remove missing values (code 99)
df = df[df["Source of drinking water"] != 99]

# Group categories and label them
replacement_dict = {
    10: 1, 11: 1, 12: 1, 13: 1, 14: 1, 20: 1, 21: 1, 30: 1, 31: 1, 41: 1,
    51: 1, 71: 1, 61: 1, 62: 1, 32: 2, 40: 2, 42: 2, 43: 2, 96: 2, 97: 2,
    92: 'Improved'  # Include code 92 in the replacement dictionary
}


# Replace the values in the column
df["Source of drinking water"] = df["Source of drinking water"].replace(replacement_dict)

# Label the categories
df["Source of drinking water"] = df["Source of drinking water"].replace({1: 'Improved', 2: 'Unimproved'})


In [31]:
# Print shape before dropping missing values
print("Shape before dropping missing values:", df.shape)

# Remove missing values (code 99)
df = df[df["Source of drinking water"] != 99]

# Print shape after dropping missing values
print("Shape after dropping missing values:", df.shape)

# Group categories and label them
replacement_dict = {
    10: 1, 11: 1, 12: 1, 13: 1, 14: 1, 20: 1, 21: 1, 30: 1, 31: 1, 41: 1,
    51: 1, 71: 1, 61: 1, 62: 1, 32: 2, 40: 2, 42: 2, 43: 2, 96: 2, 97: 2
}

# Replace the values in the column
df["Source of drinking water"] = df["Source of drinking water"].replace(replacement_dict)

# Label the categories
df["Source of drinking water"] = df["Source of drinking water"].replace({1: 'Improved', 2: 'Unimproved'})

# Print unique values after processing
print("Unique values after processing:")
print(df['Source of drinking water'].unique())

# Print value counts after processing
print("Value counts after processing:")
print(df['Source of drinking water'].value_counts())


Shape before dropping missing values: (31, 23)
Shape after dropping missing values: (31, 23)
Unique values after processing:
['Improved' 'Unimproved']
Value counts after processing:
Source of drinking water
Improved      29
Unimproved     2
Name: count, dtype: int64


toilet facility v116

In [32]:
df['v116'].unique()

array([12., 11., 31., 22., 13., 23., 41., 15.])

In [33]:
df = df.rename(columns={"v116": "Toilet Facility"})

In [34]:
# Print shape before dropping missing values
print("Shape before dropping missing values:", df.shape)

# Remove missing values (code 99)
df = df[df["Toilet Facility"] != 99]

# Remove rows with missing values
df = df.dropna(subset=["Toilet Facility"])

# Print shape after dropping missing values
print("Shape after dropping missing values:", df.shape)

# Group categories and label them
replacement_dict = {
    10: 1, 11: 1, 12: 1, 13: 1, 14: 1, 15: 1, 20: 2, 21: 2, 22: 2, 23: 2,
    30: 3, 31: 3, 41: 4, 42: 4, 43: 4, 44: 4, 96: 5, 97: 5
}

# Replace the values in the column
df["Toilet Facility"] = df["Toilet Facility"].replace(replacement_dict)

# Label the categories
df["Toilet Facility"] = df["Toilet Facility"].replace({
    1: 'Improved', 2: 'Unimproved', 3: 'No facility',
    4: 'Other', 5: 'Unknown'
})

# Print unique values after processing
print("Unique values after processing:")
print(df['Toilet Facility'].unique())

# Print value counts after processing
print("Value counts after processing:")
print(df['Toilet Facility'].value_counts())


Shape before dropping missing values: (31, 23)
Shape after dropping missing values: (31, 23)
Unique values after processing:
['Improved' 'No facility' 'Unimproved' 'Other']
Value counts after processing:
Toilet Facility
Improved       17
No facility     6
Unimproved      5
Other           3
Name: count, dtype: int64


In [35]:
df['Toilet Facility'].unique()



array(['Improved', 'No facility', 'Unimproved', 'Other'], dtype=object)

In [36]:
df['Toilet Facility'].value_counts()


Toilet Facility
Improved       17
No facility     6
Unimproved      5
Other           3
Name: count, dtype: int64

In [37]:
# Check for NaN values in the "Toilet Facility" column
print(df["Toilet Facility"].isna().sum())


0


mothers age at first birth v212

In [38]:

df['v212'].unique()

array([21., 30., 20., 27., 32., 19., 23., 25., 24., 17., 18., 22.])

In [39]:
df['v212'] = pd.cut(df['v212'], bins=[0, 19, 29, 39, 50], include_lowest=True, labels=['<20', '20-29', '30-39', '40 or above'])


In [40]:
df['v212'].value_counts()

v212
20-29          20
<20             9
30-39           2
40 or above     0
Name: count, dtype: int64

In [41]:
df = df.rename(columns={"v212": "Mother's age at first birth"})

Sex of child

In [42]:
df['b4'].unique()


array([1., 2.])

In [43]:
df = df.rename(columns={"b4": "sex of child"})

In [44]:
df['sex of child']=df['sex of child'].replace({1:'Male',2:'Female'})


In [45]:
df['sex of child'].value_counts()

sex of child
Female    17
Male      14
Name: count, dtype: int64


wealth index

In [46]:
df['v190a'].value_counts()

v190a
2.0    10
1.0     7
4.0     6
3.0     5
5.0     3
Name: count, dtype: int64

In [47]:
df = df.rename(columns={"v190a": "wealth index"})

In [48]:
df['wealth index'] = df['wealth index'].replace({1:'Poorest', 2:'Poorer', 3:'Middle', 4:'Richer', 5:'Richest'})



Months of bf

In [49]:


df = df.rename(columns={'m5': "months of bf"})

In [50]:
df['months of bf']=pd.cut(df['months of bf'] ,bins=[0,24, 100], right=False , labels=['<24','>24'] , include_lowest=True)



In [51]:
df['months of bf'].unique()

['<24', '>24']
Categories (2, object): ['<24' < '>24']

In [52]:
df['months of bf'].value_counts()

months of bf
<24    22
>24     9
Name: count, dtype: int64


Immunization

In [53]:
df = df.rename(columns={"s370b": "immunization"})

In [54]:
df['immunization'] = df['immunization'].replace({0: 'Not immunized', 1: 'Immunized'})


In [55]:
df['immunization'].value_counts()

immunization
Not immunized    31
Name: count, dtype: int64

Index to birth history

In [56]:
df = df.rename(columns={"hidx": "index to birth history"})

In [57]:
df['index to birth history'].value_counts()


index to birth history
1.0    30
2.0     1
Name: count, dtype: int64

Sex of household head

In [58]:
df = df.rename(columns={"v151": "sex of household head"})

In [59]:
df['sex of household head'].value_counts()

sex of household head
1.0    26
2.0     5
Name: count, dtype: int64

In [60]:
df['sex of household head']=df['sex of household head'].replace({1:'Male', 2:'Female'})






no of living children

In [61]:
df = df.rename(columns={"v218": "number of living children"})


In [62]:
df['number of living children'].value_counts()

number of living children
2.0    12
1.0     9
4.0     4
3.0     3
6.0     2
5.0     1
Name: count, dtype: int64

currently in union

In [63]:
df = df.rename(columns={"s301": "currently in union"})


In [64]:
df['currently in union'] = df['currently in union'].replace({0:'Never married', 1:'Currently married',2:'Married, gauna not performed',3:'Widowed',4:'Divorced',5:'Separated',6:'Deserted'})



In [65]:
df['currently in union'].value_counts()

currently in union
Currently married    31
Name: count, dtype: int64

state

In [66]:
df = df.rename(columns={"v024": "state"})


In [67]:
# Create a mapping of state codes to state names
state_code_to_name = {
    1: "Jammu & Kashmir",
    2: "Himachal Pradesh",
    3: "Punjab",
    4: "Chandigarh",
    5: "Uttarakhand",
    6: "Haryana",
    7: "Nct Of Delhi",
    8: "Rajasthan",
    9: "Uttar Pradesh",
    10: "Bihar",
    11: "Sikkim",
    12: "Arunachal Pradesh",
    13: "Nagaland",
    14: "Manipur",
    15: "Mizoram",
    16: "Tripura",
    17: "Meghalaya",
    18: "Assam",
    19: "West Bengal",
    20: "Jharkhand",
    21: "Odisha",
    22: "Chhattisgarh",
    23: "Madhya Pradesh",
    24: "Gujarat",
    25: "Dadra & Nagar Haveli And Daman & Diu",
    27: "Maharashtra",
    28: "Andhra Pradesh",
    29: "Karnataka",
    30: "Goa",
    31: "Lakshadweep",
    32: "Kerala",
    33: "Tamil Nadu",
    34: "Puducherry",
    35: "Andaman & Nicobar Islands",
    36: "Telangana",
    37: "Ladakh"
}

# Create a mapping of state names to regions
state_name_to_region = {
    "Jammu & Kashmir": "North_India",
    "Himachal Pradesh": "North_India",
    "Punjab": "North_India",
    "Chandigarh": "North_India",
    "Uttarakhand": "Central_India",
    "Haryana": "North_India",
    "Nct Of Delhi": "North_India",
    "Rajasthan": "North_India",
    "Uttar Pradesh": "Central_India",
    "Bihar": "East_India",
    "Sikkim": "NorthEast_India",
    "Arunachal Pradesh": "NorthEast_India",
    "Nagaland": "NorthEast_India",
    "Manipur": "NorthEast_India",
    "Mizoram": "NorthEast_India",
    "Tripura": "NorthEast_India",
    "Meghalaya": "NorthEast_India",
    "Assam": "NorthEast_India",
    "West Bengal": "East_India",
    "Jharkhand": "East_India",
    "Odisha": "East_India",
    "Chhattisgarh": "Central_India",
    "Madhya Pradesh": "Central_India",
    "Gujarat": "West_India",
    "Dadra & Nagar Haveli And Daman & Diu": "West_India",
    "Maharashtra": "West_India",
    "Andhra Pradesh": "South_India",
    "Karnataka": "South_India",
    "Goa": "West_India",
    "Lakshadweep": "South_India",
    "Kerala": "South_India",
    "Tamil Nadu": "South_India",
    "Puducherry": "South_India",
    "Andaman & Nicobar Islands": "South_India",
    "Telangana": "South_India",
    "Ladakh": "North_India"
}

# Replace numeric state codes with state names
df['state'] = df['state'].replace(state_code_to_name)

# Replace state names with corresponding regions
df['state'] = df['state'].replace(state_name_to_region)




In [68]:
df['state'].value_counts()


state
East_India         8
North_India        7
Central_India      6
NorthEast_India    5
South_India        3
West_India         2
Name: count, dtype: int64

mother's weight in kgs(1 decimal)

In [69]:
df = df.rename(columns={"v437": "mother's weight"})


In [70]:
import numpy as np
# First, print unique values to see the context
print(df["mother's weight"].unique())

# Update the replacement dictionary to include specific codes
# Update the replacement dictionary to include specific codes
replacement_dict = {
    9994: np.nan,
    9995: np.nan,
    9996: np.nan,
    9999: np.nan
}

# Replace specific codes with NaN in the 'mother's weight' column
df['mother\'s weight'] = df['mother\'s weight'].replace(replacement_dict)

# Drop rows with NaN values in the 'mother's weight' column
df = df.dropna(subset=['mother\'s weight'])

# Print unique values and shape to verify the changes
print(df['mother\'s weight'].unique())
print(f'Shape of df after dropping rows = {df.shape}')

# Print the value counts to check the distribution
print(df['mother\'s weight'].value_counts())


[468. 523. 482. 597. 346. 464. 485. 653. 392. 589. 497. 681. 458. 381.
 584. 367. 614. 579. 395. 496. 437. 512. 500. 549. 382. 489. 420. 413.
 404. 569.]
[468. 523. 482. 597. 346. 464. 485. 653. 392. 589. 497. 681. 458. 381.
 584. 367. 614. 579. 395. 496. 437. 512. 500. 549. 382. 489. 420. 413.
 404. 569.]
Shape of df after dropping rows = (31, 23)
mother's weight
485.0    2
468.0    1
482.0    1
597.0    1
346.0    1
523.0    1
464.0    1
653.0    1
392.0    1
589.0    1
497.0    1
681.0    1
458.0    1
381.0    1
584.0    1
367.0    1
614.0    1
579.0    1
395.0    1
496.0    1
437.0    1
512.0    1
500.0    1
549.0    1
382.0    1
489.0    1
420.0    1
413.0    1
404.0    1
569.0    1
Name: count, dtype: int64


mother's height

In [71]:
df = df.rename(columns={"v438": "mother's height"})


In [72]:
import numpy as np
# First, print unique values to see the context
print(df["mother's height"].unique())

# Update the replacement dictionary to include specific codes
# Update the replacement dictionary to include specific codes
replacement_dict = {
    9994: np.nan,
    9995: np.nan,
    9996: np.nan,
    9999: np.nan
}

# Replace specific codes with NaN in the 'mother's weight' column
df['mother\'s height'] = df['mother\'s height'].replace(replacement_dict)

# Drop rows with NaN values in the 'mother's weight' column
df = df.dropna(subset=['mother\'s height'])

# Print unique values and shape to verify the changes
print(df['mother\'s height'].unique())
print(f'Shape of df after dropping rows = {df.shape}')

# Print the value counts to check the distribution
print(df['mother\'s height'].value_counts())


[1489. 1556. 1552. 1520. 1444. 1522. 1524. 1578. 1505. 1645. 1497. 1677.
 1573. 1574. 1311. 1476. 1586. 1465. 1538. 1475. 1609. 1594. 1392. 1513.
 1511. 1453. 1510.]
[1489. 1556. 1552. 1520. 1444. 1522. 1524. 1578. 1505. 1645. 1497. 1677.
 1573. 1574. 1311. 1476. 1586. 1465. 1538. 1475. 1609. 1594. 1392. 1513.
 1511. 1453. 1510.]
Shape of df after dropping rows = (31, 23)
mother's height
1489.0    2
1578.0    2
1520.0    2
1573.0    2
1552.0    1
1522.0    1
1556.0    1
1524.0    1
1505.0    1
1645.0    1
1444.0    1
1497.0    1
1677.0    1
1574.0    1
1311.0    1
1476.0    1
1586.0    1
1465.0    1
1538.0    1
1475.0    1
1609.0    1
1594.0    1
1392.0    1
1513.0    1
1511.0    1
1453.0    1
1510.0    1
Name: count, dtype: int64


mothers bmi (calculated using mothers height and mothers weight)

In [73]:
import pandas as pd

# Assuming your dataset is stored in a pandas DataFrame called 'df'
# with columns 'mothers_height_cm' and 'mothers_weight_kg'

# Calculate BMI
df['mothers_bmi'] = df['mother\'s weight'] / ((df['mother\'s height'] / 100) ** 2)

# Round BMI to 1 decimal place
df['mothers_bmi'] = df['mothers_bmi'].round(1)




In [74]:


# Display the shape of the DataFrame
print("Shape of DataFrame:", df.shape)

# Display the value counts of the 'mothers_bmi' column
print("\nValue counts of 'mothers_bmi' column:")
print(df['mothers_bmi'].value_counts())


Shape of DataFrame: (31, 24)

Value counts of 'mothers_bmi' column:
mothers_bmi
2.2    7
2.0    5
1.8    5
2.1    3
1.7    3
2.6    2
2.3    2
2.5    2
2.8    1
1.9    1
Name: count, dtype: int64


In [75]:


df.shape

(31, 24)

In [76]:
df

Source of drinking water     hw2   Caste Mother's age at first birth  \
4                   Improved    50.0     OBC                       20-29   
19                  Improved    51.0      SC                       30-39   
27                  Improved    84.0     OBC                       20-29   
47                  Improved    37.0     OBC                       20-29   
76                  Improved    89.0      SC                       20-29   
77                  Improved   114.0      SC                       20-29   
80                  Improved   140.0     OBC                       30-39   
98                  Improved  9994.0     OBC                       20-29   
140                 Improved    79.0     OBC                         <20   
158                 Improved   144.0     OBC                       20-29   
159                 Improved   101.0     OBC                         <20   
178                 Improved   107.0  Others                       20-29   
183                 Improved    89.0  Others                       20-29   
200                 Improved    45.0      ST                         <20   
225                 Improved    92.0      SC                       20-29   
237                 Improved   153.0  Others                       20-29   
244                 Improved    73.0      SC                       20-29   
254                 Improved   114.0     OBC                       20-29   
258               Unimproved   148.0     OBC                       20-29   
275                 Improved    81.0  Others                         <20   
277                 Improved    88.0      ST                         <20   
314                 Improved   104.0      ST                         <20   
316                 Improved   118.0     OBC                         <20   
345                 Improved    88.0      ST                       20-29   
355                 Improved    91.0  Others                         <20   
425                 Improved    62.0      SC                       20-29   
426                 Improved    92.0     OBC                       20-29   
431                 Improved   106.0      SC                       20-29   
502                 Improved    61.0     OBC                         <20   
519               Unimproved    81.0      SC                       20-29   
537                 Improved   120.0      ST                       20-29   

    wealth index    v445  mother's height Toilet Facility  \
4         Middle  2111.0           1489.0        Improved   
19       Richest  2160.0           1556.0        Improved   
27        Richer  1999.0           1552.0        Improved   
47       Richest  2584.0           1520.0        Improved   
76        Poorer  1657.0           1444.0        Improved   
77       Poorest  2003.0           1522.0     No facility   
80       Richest  2086.0           1524.0        Improved   
98       Poorest  2622.0           1578.0      Unimproved   
140       Poorer  1728.0           1505.0     No facility   
158      Poorest  2177.0           1645.0        Improved   
159       Middle  2164.0           1497.0        Improved   
178       Poorer  1767.0           1677.0        Improved   
183       Poorer  2752.0           1573.0        Improved   
200      Poorest  1849.0           1574.0     No facility   
225       Poorer  2214.0           1311.0      Unimproved   
237       Richer  2343.0           1578.0        Improved   
244       Poorer  1685.0           1476.0      Unimproved   
254      Poorest  2479.0           1573.0     No facility   
258       Middle  2300.0           1586.0      Unimproved   
275       Richer  1838.0           1465.0        Improved   
277       Poorer  2097.0           1538.0     No facility   
314       Middle  2006.0           1475.0        Improved   
316      Poorest  1978.0           1609.0           Other   
345       Poorer  2164.0           1520.0           Other   
355      Poorest  2161.0           1594.0     

In [77]:
df = df.rename(columns={"v445": "body mass index"})


child height

In [78]:
df = df.rename(columns={"hw3": "child's height(in cms)(one decimal)"})


In [79]:
import numpy as np
# First, print unique values to see the context
print(df["child's height(in cms)(one decimal)"].unique())

# Update the replacement dictionary to include specific codes
# Update the replacement dictionary to include specific codes
replacement_dict = {
    9994: np.nan,
    9995: np.nan,
    9996: np.nan,
    9999: np.nan
}

# Replace specific codes with NaN in the 'mother's weight' column
df['child\'s height(in cms)(one decimal)'] = df['child\'s height(in cms)(one decimal)'].replace(replacement_dict)

# Drop rows with NaN values in the 'mother's weight' column
df = df.dropna(subset=['child\'s height(in cms)(one decimal)'])

# Print unique values and shape to verify the changes
print(df['child\'s height(in cms)(one decimal)'].unique())
print(f'Shape of df after dropping rows = {df.shape}')

# Print the value counts to check the distribution
print(df['child\'s height(in cms)(one decimal)'].value_counts())


[ 558.  583.  741.  542.  702.  867.  875. 9994.  752.  814.  871.  721.
  784.  638.  868.  863.  686.  852.  847.  676.  748.  773.  892.  886.
  764.  611.  720.  842.  652.  751.  865.]
[558. 583. 741. 542. 702. 867. 875. 752. 814. 871. 721. 784. 638. 868.
 863. 686. 852. 847. 676. 748. 773. 892. 886. 764. 611. 720. 842. 652.
 751. 865.]
Shape of df after dropping rows = (30, 24)
child's height(in cms)(one decimal)
558.0    1
583.0    1
741.0    1
542.0    1
702.0    1
867.0    1
875.0    1
752.0    1
814.0    1
871.0    1
721.0    1
784.0    1
638.0    1
868.0    1
863.0    1
686.0    1
852.0    1
847.0    1
676.0    1
748.0    1
773.0    1
892.0    1
886.0    1
764.0    1
611.0    1
720.0    1
842.0    1
652.0    1
751.0    1
865.0    1
Name: count, dtype: int64


child's weight

In [80]:
df = df.rename(columns={"hw2": "child's weight(in kgs)(one decimal)"})


In [81]:
import numpy as np
# First, print unique values to see the context
print(df["child's weight(in kgs)(one decimal)"].unique())

# Update the replacement dictionary to include specific codes
# Update the replacement dictionary to include specific codes
replacement_dict = {
    9994: np.nan,
    9995: np.nan,
    9996: np.nan,
    9999: np.nan
}

# Replace specific codes with NaN in the 'mother's weight' column
df['child\'s weight(in kgs)(one decimal)'] = df['child\'s weight(in kgs)(one decimal)'].replace(replacement_dict)

# Drop rows with NaN values in the 'mother's weight' column
df = df.dropna(subset=['child\'s weight(in kgs)(one decimal)'])

# Print unique values and shape to verify the changes
print(df['child\'s weight(in kgs)(one decimal)'].unique())
print(f'Shape of df after dropping rows = {df.shape}')

# Print the value counts to check the distribution
print(df['child\'s weight(in kgs)(one decimal)'].value_counts())


[ 50.  51.  84.  37.  89. 114. 140.  79. 144. 101. 107.  45.  92. 153.
  73. 148.  81.  88. 104. 118.  91.  62. 106.  61. 120.]
[ 50.  51.  84.  37.  89. 114. 140.  79. 144. 101. 107.  45.  92. 153.
  73. 148.  81.  88. 104. 118.  91.  62. 106.  61. 120.]
Shape of df after dropping rows = (30, 24)
child's weight(in kgs)(one decimal)
89.0     2
114.0    2
88.0     2
81.0     2
92.0     2
37.0     1
50.0     1
84.0     1
51.0     1
144.0    1
79.0     1
140.0    1
107.0    1
45.0     1
153.0    1
73.0     1
101.0    1
148.0    1
104.0    1
118.0    1
91.0     1
62.0     1
106.0    1
61.0     1
120.0    1
Name: count, dtype: int64


In [82]:
df.to_csv('preprocessed_data1.csv')

In [84]:
if 'Unnamed: 0' in df.columns:
    df = df.drop('Unnamed: 0', axis=1)
else:
    print("'Unnamed: 0' column not found in DataFrame")


'Unnamed: 0' column not found in DataFrame


In [85]:
print(df.columns)


Index(['Source of drinking water', 'child's weight(in kgs)(one decimal)',
       'Caste', 'Mother's age at first birth', 'wealth index',
       'body mass index', 'mother's height', 'Toilet Facility',
       'number of living children', 'sex of household head',
       'Mother's Occupation', 'Father's Education', 'Father's Occupation',
       'sex of child', 'child's height(in cms)(one decimal)',
       'currently in union', 'immunization', 'mother's weight', 'state',
       'index to birth history', 'Area', 'Religion', 'months of bf',
       'mothers_bmi'],
      dtype='object')


In [86]:
# If 'Unnamed: 0' is an index column, you can set the index_col parameter
df = pd.read_csv('/content/preprocessed_data1.csv', index_col=0)


In [87]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]


In [88]:
df.describe()

child's weight(in kgs)(one decimal)  body mass index  mother's height  \
count                            30.000000        30.000000        30.000000   
mean                             93.400000      2084.166667      1522.366667   
std                              30.118845       268.920458        72.550331   
min                              37.000000      1657.000000      1311.000000   
25%                              79.500000      1864.500000      1489.000000   
50%                              90.000000      2091.500000      1520.000000   
75%                             112.250000      2196.500000      1573.000000   
max                             153.000000      2752.000000      1677.000000   

       number of living children  child's height(in cms)(one decimal)  \
count                  30.000000                            30.000000   
mean                    2.333333                           758.133333   
std                     1.397864                           104.715619   
min                     1.000000                           542.000000   
25%                     1.000000                           690.000000   
50%                     2.000000                           758.000000   
75%                     3.000000                           860.250000   
max                     6.000000                           892.000000   

       mother's weight  index to birth history  mothers_bmi  
count        30.000000               30.000000    30.000000  
mean        485.266667                1.033333     2.090000  
std          83.468736                0.182574     0.277116  
min         346.000000                1.000000     1.700000  
25%         414.750000                1.000000     1.825000  
50%         485.000000                1.000000     2.100000  
75%         542.500000                1.000000     2.200000  
max         681.000000                2.000000     2.800000

In [89]:
import pandas as pd

# Assuming your dataset is in a DataFrame called df
# Let's first look at the data
print(df.describe())

# Dropping the 'Unnamed: 0' column if it exists
if 'Unnamed: 0' in df.columns:
    df = df.drop('Unnamed: 0', axis=1)

# Checking unique values and shapes
print(df['number of living children'].unique())
print(f'shape of original df = {df.shape}')

# Handling 'number of living children' by replacing outliers and dropping them
df["number of living children"] = df["number of living children"].replace({10:999, 11:999, 12:999, 13:999})
indexNames = df[df['number of living children'] == 999].index
df.drop(indexNames , inplace=True)
print(df['number of living children'].unique())
print(f'shape of new df = {df.shape}')

# Checking and cleaning 'index to birth history'
print(df['index to birth history'].unique())
print(f'shape of original df = {df.shape}')
indexNames = df[df['index to birth history'] == 4].index
df.drop(indexNames , inplace=True)
print(df['index to birth history'].unique())
print(f'shape of new df = {df.shape}')

# Now let's take a look at other columns and their unique values
print(df['child\'s weight(in kgs)(one decimal)'].unique())
print(df['body mass index'].unique())
print(df['mother\'s height'].unique())
print(df['child\'s height(in cms)(one decimal)'].unique())
print(df['mother\'s weight'].unique())
print(df['mothers_bmi'].unique())

# If there are outliers or invalid values, we should handle them similarly
# For instance, let's handle 'child\'s weight(in kgs)(one decimal)'
indexNames = df[df['child\'s weight(in kgs)(one decimal)'] > 999].index
df.drop(indexNames , inplace=True)

# Checking unique values again after cleaning
print(df['child\'s weight(in kgs)(one decimal)'].unique())
print(f'shape of final df = {df.shape}')

# Describe the cleaned DataFrame
print(df.describe())


       child's weight(in kgs)(one decimal)  body mass index  mother's height  \
count                            30.000000        30.000000        30.000000   
mean                             93.400000      2084.166667      1522.366667   
std                              30.118845       268.920458        72.550331   
min                              37.000000      1657.000000      1311.000000   
25%                              79.500000      1864.500000      1489.000000   
50%                              90.000000      2091.500000      1520.000000   
75%                             112.250000      2196.500000      1573.000000   
max                             153.000000      2752.000000      1677.000000   

       number of living children  child's height(in cms)(one decimal)  \
count                  30.000000                            30.000000   
mean                    2.333333                           758.133333   
std                     1.397864                           1

In [90]:

from sklearn import preprocessing

In [91]:

dfl = pd.DataFrame()

STATE
AREA
RELIGION
CAASTE
Father's Education
Father's Occupation
Mother's Occupation
Source of drinking water
Toilet Facility
Mother's age at first birth
sex of child
wealth index
months of bf
immunization
sex of household head
currently in union

In [96]:
label_encoder = preprocessing.LabelEncoder()
dfl['state']= label_encoder.fit_transform(df['state'])
dfl['Area']= label_encoder.fit_transform(df['Area'])
dfl['Religion']= label_encoder.fit_transform(df['Religion'])
dfl['Caste']= label_encoder.fit_transform(df['Caste'])
dfl['Father\'s Education']= label_encoder.fit_transform(df['Father\'s Education'])
dfl['Father\'s Occupation']= label_encoder.fit_transform(df['Father\'s Occupation'])
#dfl['child\'s height(in cms)(one decimal)']= label_encoder.fit_transform(df['child\'s height(in cms)(one decimal)'])
dfl['Mother\'s Occupation']= label_encoder.fit_transform(df['Mother\'s Occupation'])
#dfl['exposure to mass media']= label_encoder.fit_transform(df['exposure to mass media'])
dfl['Source of drinking water']= label_encoder.fit_transform(df['Source of drinking water'])
dfl['Toilet Facility'] = label_encoder.fit_transform(df['Toilet Facility'])
dfl['Mother\'s age at first birth']= label_encoder.fit_transform(df['Mother\'s age at first birth'])
#dfl['mothers_bmi']= label_encoder.fit_transform(df['mothers_bmi'])
#dfl['child\'s age']= label_encoder.fit_transform(df['child\'s age'])
dfl['sex of child']= label_encoder.fit_transform(df['sex of child'])
#dfl['child\'s weight(in kgs)(one decimal)']= label_encoder.fit_transform(df['child\'s weight(in kgs)(one decimal)'])
#dfl['initiation of bf(early initiation)']= label_encoder.fit_transform(df['initiation of bf(early initiation)'])
dfl['wealth index']= label_encoder.fit_transform(df['wealth index'])
dfl['months of bf']= label_encoder.fit_transform(df['months of bf'])
dfl['immunization']= label_encoder.fit_transform(df['immunization'])
dfl['sex of household head']= label_encoder.fit_transform(df['sex of household head'])
dfl['currently in union']= label_encoder.fit_transform(df['currently in union'])
#dfl['mother\'s height']= label_encoder.fit_transform(df['mother\'s height'])

dfl['child\'s weight(in kgs)(one decimal)'] = df['child\'s weight(in kgs)(one decimal)']
dfl['body mass index'] = df['body mass index']
dfl['mother\'s height'] = df['mother\'s height']
dfl['number of living children'] = df['number of living children']
dfl['child\'s height(in cms)(one decimal)'] = df['child\'s height(in cms)(one decimal)']
dfl['mother\'s weight'] = df['mother\'s weight']
dfl['index to birth history'] = df['index to birth history']
dfl['mothers_bmi'] = df['mothers_bmi']

In [97]:

dfl.describe()

state       Area   Religion     Caste  Father's Education  \
count  30.000000  30.000000  30.000000  30.00000           30.000000   
mean    2.000000   0.200000   1.100000   1.20000            2.266667   
std     1.531283   0.406838   0.402578   1.15669            1.048261   
min     0.000000   0.000000   0.000000   0.00000            0.000000   
25%     1.000000   0.000000   1.000000   0.00000            2.000000   
50%     2.000000   0.000000   1.000000   1.00000            3.000000   
75%     3.000000   0.000000   1.000000   2.00000            3.000000   
max     5.000000   1.000000   2.000000   3.00000            3.000000   

       Father's Occupation  Mother's Occupation  Source of drinking water  \
count            30.000000            30.000000                 30.000000   
mean              2.633333             2.933333                  0.066667   
std               1.809617             1.659525                  0.253708   
min               0.000000             0.000000                  0.000000   
25%               1.000000             2.000000                  0.000000   
50%               2.000000             4.000000                  0.000000   
75%               4.000000             4.000000                  0.000000   
max               5.000000             4.000000                  1.000000   

       Toilet Facility  Mother's age at first birth  ...  \
count        30.000000                    30.000000  ...   
mean          0.800000                     0.666667  ...   
std           1.095445                     0.922266  ...   
min           0.000000                     0.000000  ...   
25%           0.000000                     0.000000  ...   
50%           0.000000                     0.000000  ...   
75%           1.000000                     2.000000  ...   
max           3.000000                     2.000000  ...   

       sex of household head  currently in union  \
count              30.000000                30.0   
mean                0.833333                 0.0   
std                 0.379049                 0.0   
min                 0.000000                 0.0   
25%                 1.000000                 0.0   
50%                 1.000000                 0.0   
75%                 1.000000                 0.0   
max                 1.000000                 0.0   

       child's weight(in kgs)(one decimal)  body mass index  mother's height  \
count                             3.000000         3.000000         3.000000   
mean                             61.666667      2090.000000      1532.333333   
std                              19.347696        82.528783        37.581024   
min                              50.000000      1999.000000      1489.000000   
25%                              50.500000      2055.000000      1520.500000   
50%                              51.000000      2111.000000      1552.000000   
75%                              67.500000      2135.500000      1554.000000   
max                              84.000000      2160.000000      1556.000000   

       number of living children  child's height(in cms)(one decimal)  \
count                   3.000000                             3.000000   
mean                    1.666667                           627.333333   
std                     0.577350                            99.228692   
min                     1.000000                           558.000000   
25%                     1.500000                           570.500000   
50%                     2.000000                           583.000000   
75%                     2.000000                           662.000000   
max                     2.000000                           741.000000   

       mother's weight  index to birth history  mothers_bmi  
count         3.000000                     3.0         3.00  
mean        491.000000                     1.0         2.10  
std          28.583212                     0.0         0.10  
min         468.000000         

In [98]:

df.to_csv('final_data_dhs.csv')
