<a href="https://colab.research.google.com/github/atgdot/child_malnutrition_02/blob/main/preprocessed_data_dhs_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [11]:
import cudf

# Define the features to keep
features_to_keep = [
    "v130", "v024", "v116", "v113", "v025",  "s370b",
    "s116", "v190a", "b4", "v151", "hidx", "v218", "m5", "s301", "v212", "v445",
    "v437", "v438","hw1","hw2","hw3","v444a","v440","v441","v442","hw9","h211","hw12"]

# Read the CSV file into a pandas DataFrame
df = cudf.read_csv("/content/drive/MyDrive/IAKR7EDT/IAKR7EDT.csv")

# Drop all features except the ones specified in features_to_keep
dropped_features = list(set(df.columns) - set(features_to_keep))
df.drop(dropped_features, axis=1, inplace=True)

# Save the modified DataFrame to a new CSV file
df.to_csv("/content/reduced_features_230k.csv", index=False)

# Print the DataFrame with dropped features (optional)
print(df)


        v024  v025  v113  v116  v130  v151 v190a  v212  v218   v437  ...  \
0       <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>   <NA>  ...   
1          1     2    12  44.0     2     1     2    26     4  438.0  ...   
2          1     2    12  44.0     2     1     1    33     1  753.0  ...   
3          1     2    12  44.0     2     1     3    29     1  655.0  ...   
4          1     2    12  12.0     2     1     3    26     2  605.0  ...   
...      ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  ...   
232915    37     1    61  44.0     2     1     1    22     1  506.0  ...   
232916    37     1    61  44.0     2     1     2    31     1  624.0  ...   
232917    37     1    61  12.0     2     1     3    29     2  613.0  ...   
232918    37     1    61  12.0     2     1     3    28     1  485.0  ...   
232919    37     1    97  97.0     2     1     1    28     1  504.0  ...   

          m5  hidx   hw1    hw2     hw3      hw9     hw12  s116  s301 s370b  
0       <

In [12]:
df.isnull().sum()

v024         1
v025         1
v113         1
v116         2
v130         1
v151         1
v190a        1
v212         1
v218         1
v437        79
v438        83
v440      5911
v441      5911
v442      5923
v444a     5923
v445      5911
b4           1
m5       46739
hidx     95522
hw1      11658
hw2      14882
hw3      15357
hw9      21932
hw12     21791
s116     10684
s301         1
s370b    70114
dtype: int64

In [13]:
df.isna().sum()

v024         1
v025         1
v113         1
v116         2
v130         1
v151         1
v190a        1
v212         1
v218         1
v437        79
v438        83
v440      5911
v441      5911
v442      5923
v444a     5923
v445      5911
b4           1
m5       46739
hidx     95522
hw1      11658
hw2      14882
hw3      15357
hw9      21932
hw12     21791
s116     10684
s301         1
s370b    70114
dtype: int64

In [14]:
df = df.dropna()


In [15]:
df

v024  v025  v113  v116  v130  v151  v190a  v212  v218   v437  ...  \
7          1     2    14  13.0     2     1      3    25     3  600.0  ...   
8          1     2    11  12.0     2     1      5    32     1  668.0  ...   
12         1     2    14  12.0     2     1      4    35     1  602.0  ...   
16         1     2    11  12.0     2     1      5    30     1  584.0  ...   
20         1     2    11  12.0     2     1      2    26     5  811.0  ...   
...      ...   ...   ...   ...   ...   ...    ...   ...   ...    ...  ...   
232872    37     2    21  44.0     2     1      3    26     3  532.0  ...   
232878    37     2    21  44.0     2     1      2    16     4  551.0  ...   
232892    37     1    61  12.0     2     1      2    26     2  569.0  ...   
232895    37     1    61  12.0     2     1      2    28     2  655.0  ...   
232907    37     1    11  44.0     2     1      1    24     4  577.0  ...   

          m5  hidx   hw1    hw2    hw3      hw9     hw12  s116  s301  s370b  
7       11.0   1.0  11.0  133.0  766.0  13226.0  13065.0   4.0     1    0.0  
8        3.0   1.0   3.0  142.0  792.0  99998.0  99998.0   4.0     0    1.0  
12      12.0   1.0  12.0   78.0  739.0   7899.0   8344.0   3.0     1    0.0  
16      32.0   1.0  32.0  101.0  846.0   7440.0   8554.0   4.0     1    0.0  
20      29.0   1.0  29.0  101.0  874.0   7761.0   8136.0   4.0     1    0.0  
...      ...   ...   ...    ...    ...      ...      ...   ...   ...    ...  
232872  13.0   1.0  13.0   93.0  805.0   8808.0   8443.0   2.0     1    0.0  
232878  25.0   1.0  25.0  110.0  785.0   9066.0  10496.0   2.0     1    0.0  
232892  10.0   1.0  10.0   77.0  731.0   8496.0   8350.0   2.0     1    1.0  
232895  14.0   1.0  14.0   73.0  799.0   7203.0   6846.0   2.0     1    0.0  
232907  27.0   1.0  27.0  117.0  998.0   9410.0   7639.0   2.0     1    1.0  

[73172 rows x 27 columns]

CAlculation of BMI , HAZ , WAZ , WHZ

In [10]:
def calculate_bmi(weight_gms, height_cms):
    # Convert height from centimeters to meters
    height_meters = height_cms / 100
    # Calculate BMI using the formula: weight (kg) / (height (m))^2
    bmi = weight_gms*10 / (height_meters ** 2)
    return bmi

# Calculate BMI for each datapoint and store in a new column 'bmi'
df['bmi'] = df.apply(lambda row: calculate_bmi(row['hw2'], row['hw3']), axis=1)

# Save the modified DataFrame to a new CSV file
df.to_csv("/content/reduced_feature_230k.csv", index=False)

# Print the DataFrame with the updated 'bmi' column (optional)
print(df)


ValueError: user defined function compilation failed.

In [ ]:
mean_height = 70.0  # Mean height for age
std_dev_height = 4.0  # Standard deviation for height
mean_weight = 10.0  # Mean weight for age
std_dev_weight = 2.0  # Standard deviation for weight

# Calculate Z-scores
df['H/A'] = (df["hw3"] - mean_height) / std_dev_height
df['W/A'] = (df["hw2"] - mean_weight) / std_dev_weight
df['W/H'] = ((df["hw2"] * 10) - mean_weight) / std_dev_weight

# Save the updated DataFrame back to a new CSV file
df.to_csv('updated_dataset.csv', index=False)  # Save the updated dataset to a new file 'updated_dataset.csv'

In [ ]:
df

v113    hw2  s116  v212  v190a  v444a   hw1    v445    v438  v116  ...  \
4       21   50.0   3.0    21      3  -98.0   2.0  2111.0  1489.0  12.0  ...   
19      12   51.0   1.0    30      5  -91.0   3.0  2160.0  1556.0  11.0  ...   
27      11   84.0   3.0    20      4 -125.0   8.0  1999.0  1552.0  12.0  ...   
47      21   37.0   3.0    27      5   46.0   2.0  2584.0  1520.0  12.0  ...   
76      21   89.0   1.0    20      2 -236.0  10.0  1657.0  1444.0  12.0  ...   
...    ...    ...   ...   ...    ...    ...   ...     ...     ...   ...  ...   
2268    12  112.0   2.0    21      2   -5.0  29.0  2570.0  1519.0  12.0  ...   
2276    21   96.0   3.0    19      1   89.0  26.0  2738.0  1539.0  31.0  ...   
2283    97   33.0   3.0    22      4 -116.0   3.0  1912.0  1577.0  97.0  ...   
2285    11   61.0   1.0    18      4  -97.0   7.0  1998.0  1504.0  11.0  ...   
2310    97   59.0   3.0    20      3   87.0   4.0  2772.0  1475.0  97.0  ...   

       v437  v024  hidx  v025  v130    m5        bmi     H/A   W/A    W/H  
4     468.0    10   1.0     1     2   2.0  16.058375  122.00  20.0  245.0  
19    523.0     8   1.0     1     1   3.0  15.004899  128.25  20.5  250.0  
27    482.0     5   1.0     2     1   8.0  15.298289  167.75  37.0  415.0  
47    597.0    21   1.0     2     1   2.0  12.595144  118.00  13.5  180.0  
76    346.0    10   1.0     2     1  10.0  18.059918  158.00  39.5  440.0  
...     ...   ...   ...   ...   ...   ...        ...     ...   ...    ...  
2268  593.0    12   1.0     1    96  29.0  12.357884  220.50  51.0  555.0  
2276  649.0     9   1.0     2     1   9.0   9.429505  234.75  43.0  475.0  
2283  476.0    29   1.0     2     1   3.0   6.295595  163.50  11.5  160.0  
2285  452.0    27   1.0     1     1   7.0  14.572071  144.25  25.5  300.0  
2310  603.0    10   1.0     2     1   4.0  15.250049  138.00  24.5  290.0  

[133 rows x 34 columns]

In [ ]:
df["H/A"]=df["H/A"].replace({9998.0:9999.0, 9996.0:9999.0, 9997.0:9999.0})
indexNames = df[df['H/A'] == 9999.0].index
df.drop(indexNames , inplace=True)
print(df.shape)
print(df['H/A'].max())
print(df['H/A'].min())

(133, 34)
234.75
83.75


In [ ]:
print(df['H/A'].unique())
df['H/A'] = df['H/A']/100
print(df['H/A'].unique())
# df['H/A']=pd.cut(df['H/A'], bins=[-6.5,-2, 6.5], labels=[1,0], include_lowest=True)
# print(df['H/A'].unique())

[122.   128.25 167.75 118.   158.   199.25 201.25 170.5  186.   200.25
 162.75 178.5  142.   199.5  198.25 154.   195.5  194.25 151.5  169.5
 175.75 205.5  204.   173.5  135.25 162.5  193.   145.5  170.25 198.75
 221.5  197.25 143.25 147.75 153.   160.25 125.75 167.5  186.5  153.25
 144.5  195.   173.   165.5  185.75 162.25 212.5  171.   163.5  194.5
 118.75 155.75 202.25 158.25 183.   152.5  188.5  107.5  168.75 215.5
 180.75 172.   164.5  165.25 205.75 170.   181.75 123.25 112.   210.5
 145.25 161.75 163.   193.75 182.   180.5  160.   228.   206.75 163.75
 195.25 183.5  187.75 143.   156.75 114.   143.75 221.75 200.5  201.5
 209.25  83.75 139.5  171.75 175.5  210.   190.5  138.75 188.   125.
 140.25 126.25 146.5  164.   171.5  158.5  182.75 192.75 131.   156.25
 182.5  220.5  234.75 144.25 138.  ]
[1.22   1.2825 1.6775 1.18   1.58   1.9925 2.0125 1.705  1.86   2.0025
 1.6275 1.785  1.42   1.995  1.9825 1.54   1.955  1.9425 1.515  1.695
 1.7575 2.055  2.04   1.735  1.3525 1.625  1.93 

In [ ]:
df['W/A'].max()

73.5

In [ ]:
# print(df['W/H'].unique())
df['W/H'] = df['W/H']/100
print(df['W/H'].unique())
# df['W/H']=pd.cut(df['W/H'], bins=[-6.5,-2,6.5], labels=[1,0], include_lowest=True)
# print(df['W/H'].unique())

[2.45 2.5  4.15 1.8  4.4  5.65 6.95 3.9  7.15 5.   5.3  2.2  4.55 7.6
 3.6  7.35 4.   4.35 5.15 5.85 4.5  3.05 5.25 3.   5.95 4.95 5.4  2.9
 3.7  3.2  4.85 3.65 3.45 3.5  5.2  4.7  4.25 4.2  3.3  5.35 1.7  3.4
 1.15 4.9  4.3  5.1  4.6  2.8  5.9  3.55 3.95 3.75 6.1  4.8  3.8  6.05
 5.7  6.65 3.35 3.25 1.55 7.8  6.7  1.5  4.1  5.05 4.75 2.7  3.85 5.5
 5.45 2.05 5.55 1.6 ]


In [ ]:
df['W/H'].min()

1.15

In [ ]:
# print(df['Bmi'].unique())
df['bmi'] = df['Bmi']/100
print(df['bmi'].unique())
# df['Bmi']=pd.cut(df['Bmi'], bins=[-6.5,-2,6.5], labels=[1,0], include_lowest=True)
# print(df['Bmi'].unique())

KeyError: 'Bmi'

In [ ]:
df['Bmi'].max()

Variables

father's education v701

In [ ]:
print(df['v701'].unique())

[2. 3. 0. 1.]


In [ ]:

print(df['v701'].unique())
print(f'shape of original df = {df.shape}')
df["v701"]=df["v701"].replace({9:8, 0:'No education', 1:'Primary education', 2:'Secondary education', 3:'Higher education'})
indexNames = df[df['v701'] == 8].index
df.drop(indexNames , inplace=True)
print(df['v701'].unique())
print(f'shape of original df = {df.shape}')

[2. 3. 0. 1.]
shape of original df = (133, 34)
['Secondary education' 'Higher education' 'No education'
 'Primary education']
shape of original df = (133, 34)


In [ ]:
df['v701'].value_counts()

v701
Secondary education    70
Higher education       24
No education           24
Primary education      15
Name: count, dtype: int64

In [ ]:
df = df.rename(columns={"v701": "Father's Education"})

father's occupation v705

In [ ]:
print(df['v705'].unique())
df['v705']=df['v705'].replace({0:'unemployed',1:'professional',2:'clerical',3:'sales',4:'self employed',5:'Rgri',6:'household',7:'services' ,8:'skilled labour', 99.0:'dont know', 98.0:'dont know'})



[4. 5. 7. 6. 1. 9. 3.]


In [ ]:
# First, print unique values to see the context
print(df['v705'].unique())

# Update the replacement dictionary to include 9
replacement_dict = {
    0: 'unemployed',
    1: 'professional',
    2: 'clerical',
    3: 'sales',
    4: 'self employed',
    5: 'Rgri',
    6: 'household',
    7: 'services',
    8: 'skilled labour',
    9: 'other',  # Assuming 9 represents 'other'
    99.0: 'dont know',
    98.0: 'dont know'
}

# Use .loc to avoid the SettingWithCopyWarning
df.loc[:, 'v705'] = df['v705'].replace(replacement_dict)

# Drop rows where v705 is 'dont know'
df = df[df['v705'] != 'dont know']

# Print unique values and shape to verify the changes
print(df['v705'].unique())
print(f'shape of df after drop = {df.shape}')

# Print the value counts to check the distribution
print(df['v705'].value_counts())


['self employed' 'Rgri' 'services' 'household' 'professional' 9.0 'sales']
['self employed' 'Rgri' 'services' 'household' 'professional' 'other'
 'sales']
shape of df after drop = (133, 34)
v705
services         47
household        43
self employed    14
other            10
Rgri              9
professional      7
sales             3
Name: count, dtype: int64


In [ ]:
df = df.rename(columns={"v705": "Father's Occupation"})

mothers occupation v717

In [ ]:
# First, print unique values to see the context
print(df['v717'].unique())

# Update the replacement dictionary to include 9
replacement_dict = {
    0: 'unemployed',
    1: 'professional',
    2: 'clerical',
    3: 'sales',
    4: 'self employed',
    5: 'Rgri',
    6: 'household',
    7: 'services',
    8: 'skilled labour',
    9: 'other',  # Assuming 9 represents 'other'
    99.0: 'dont know',
    98.0: 'dont know'
}

# Use .loc to avoid the SettingWithCopyWarning
df.loc[:, 'v717'] = df['v717'].replace(replacement_dict)

# Drop rows where v705 is 'dont know'
df = df[df['v717'] != 'dont know']

# Print unique values and shape to verify the changes
print(df['v717'].unique())
print(f'shape of df after drop = {df.shape}')

# Print the value counts to check the distribution
print(df['v717'].value_counts())


[0. 6. 4. 1. 9. 7. 5.]
['unemployed' 'household' 'self employed' 'professional' 'other'
 'services' 'Rgri']
shape of df after drop = (133, 34)
v717
unemployed       103
household         16
self employed      3
professional       3
services           3
Rgri               3
other              2
Name: count, dtype: int64


In [ ]:
df = df.rename(columns={"v717": "Mother's Occupation"})

area v025

In [ ]:

print(df['v025'].unique())
df['v025'] = df['v025'].replace({1:'Urban', 2:'Rural'})
print(df['v025'].unique())
print(df['v025'].value_counts())


[1 2]
['Urban' 'Rural']
v025
Rural    109
Urban     24
Name: count, dtype: int64


In [ ]:
df = df.rename(columns={"v025": "Area"})


religion v130

In [ ]:
print(df['v130'].unique())
df['v130']=df['v130'].replace({1:'Hindu',2:'Muslim',3:'Christian',4:'Sikh',5:'Others',6:'Others',10:'Others' ,9:'Others', 99:'Others', 96:'Others'})


[ 2  1  3  6 96  4]


In [ ]:
print(df['v130'].unique())
print(f'v130 = {df.shape}')


['Muslim' 'Hindu' 'Christian' 'Others' 'Sikh']
v130 = (133, 34)


In [ ]:
df['v130'].value_counts()

v130
Hindu        101
Muslim        19
Christian      8
Others         4
Sikh           1
Name: count, dtype: int64

In [ ]:

df = df.rename(columns={"v130": "Religion"})

caste s116

In [ ]:


df['s116'].unique()

array([3., 1., 4., 2.])

In [ ]:
print(df['s116'].unique())
print(f'shape of original df = {df.shape}')
df["s116"]=df["s116"].replace({8.0:9})
indexNames = df[df['s116'] == 9].index
df.drop(indexNames , inplace=True)
print(df['s116'].unique())
print(f'shape of new df = {df.shape}')

[3. 1. 4. 2.]
shape of original df = (133, 34)
[3. 1. 4. 2.]
shape of new df = (133, 34)


In [ ]:


df['s116']=df['s116'].replace({1:'SC',2:'ST',3:'OBC',4:'Others'})

In [ ]:

df['s116'].value_counts()

s116
OBC       50
SC        32
Others    26
ST        25
Name: count, dtype: int64

In [ ]:
df = df.rename(columns={"s116": "Caste"})

source of drinking water v113

In [ ]:
df['v113'].unique()

array([21, 12, 11, 14, 71, 31, 32, 92, 97, 13, 61, 43])

In [ ]:


df = df.rename(columns={"v113": "Source of drinking water"})

In [ ]:
# Remove missing values (code 99)
df = df[df["Source of drinking water"] != 99]

# Group categories and label them
replacement_dict = {
    10: 1, 11: 1, 12: 1, 13: 1, 14: 1, 20: 1, 21: 1, 30: 1, 31: 1, 41: 1,
    51: 1, 71: 1, 61: 1, 62: 1, 32: 2, 40: 2, 42: 2, 43: 2, 96: 2, 97: 2,
    92: 'Improved'  # Include code 92 in the replacement dictionary
}


# Replace the values in the column
df["Source of drinking water"] = df["Source of drinking water"].replace(replacement_dict)

# Label the categories
df["Source of drinking water"] = df["Source of drinking water"].replace({1: 'Improved', 2: 'Unimproved'})


In [ ]:
# Print shape before dropping missing values
print("Shape before dropping missing values:", df.shape)

# Remove missing values (code 99)
df = df[df["Source of drinking water"] != 99]

# Print shape after dropping missing values
print("Shape after dropping missing values:", df.shape)

# Group categories and label them
replacement_dict = {
    10: 1, 11: 1, 12: 1, 13: 1, 14: 1, 20: 1, 21: 1, 30: 1, 31: 1, 41: 1,
    51: 1, 71: 1, 61: 1, 62: 1, 32: 2, 40: 2, 42: 2, 43: 2, 96: 2, 97: 2
}

# Replace the values in the column
df["Source of drinking water"] = df["Source of drinking water"].replace(replacement_dict)

# Label the categories
df["Source of drinking water"] = df["Source of drinking water"].replace({1: 'Improved', 2: 'Unimproved'})

# Print unique values after processing
print("Unique values after processing:")
print(df['Source of drinking water'].unique())

# Print value counts after processing
print("Value counts after processing:")
print(df['Source of drinking water'].value_counts())


Shape before dropping missing values: (133, 34)
Shape after dropping missing values: (133, 34)
Unique values after processing:
['Improved' 'Unimproved']
Value counts after processing:
Source of drinking water
Improved      119
Unimproved     14
Name: count, dtype: int64


toilet facility v116

In [ ]:
df['v116'].unique()

array([12., 11., 31., 13., 23., 41., 22., 15., 97., 14.])

In [ ]:
df = df.rename(columns={"v116": "Toilet Facility"})

In [ ]:
# Print shape before dropping missing values
print("Shape before dropping missing values:", df.shape)

# Remove missing values (code 99)
df = df[df["Toilet Facility"] != 99]

# Remove rows with missing values
df = df.dropna(subset=["Toilet Facility"])

# Print shape after dropping missing values
print("Shape after dropping missing values:", df.shape)

# Group categories and label them
replacement_dict = {
    10: 1, 11: 1, 12: 1, 13: 1, 14: 1, 15: 1, 20: 2, 21: 2, 22: 2, 23: 2,
    30: 3, 31: 3, 41: 4, 42: 4, 43: 4, 44: 4, 96: 5, 97: 5
}

# Replace the values in the column
df["Toilet Facility"] = df["Toilet Facility"].replace(replacement_dict)

# Label the categories
df["Toilet Facility"] = df["Toilet Facility"].replace({
    1: 'Improved', 2: 'Unimproved', 3: 'No facility',
    4: 'Other', 5: 'Unknown'
})

# Print unique values after processing
print("Unique values after processing:")
print(df['Toilet Facility'].unique())

# Print value counts after processing
print("Value counts after processing:")
print(df['Toilet Facility'].value_counts())


Shape before dropping missing values: (133, 34)
Shape after dropping missing values: (133, 34)
Unique values after processing:
['Improved' 'No facility' 'Unimproved' 'Other' 'Unknown']
Value counts after processing:
Toilet Facility
Improved       72
No facility    30
Unimproved     14
Other           9
Unknown         8
Name: count, dtype: int64


In [ ]:
df['Toilet Facility'].unique()



array(['Improved', 'No facility', 'Unimproved', 'Other', 'Unknown'],
      dtype=object)

In [ ]:
df['Toilet Facility'].value_counts()


Toilet Facility
Improved       72
No facility    30
Unimproved     14
Other           9
Unknown         8
Name: count, dtype: int64

In [ ]:
# Check for NaN values in the "Toilet Facility" column
print(df["Toilet Facility"].isna().sum())


0


mothers age at first birth v212

In [ ]:

df['v212'].unique()

array([21, 30, 20, 27, 32, 19, 23, 25, 24, 17, 18, 22, 15, 26, 29, 28, 16,
       31])

In [ ]:
df['v212'] = pd.cut(df['v212'], bins=[0, 19, 29, 39, 50], include_lowest=True, labels=['<20', '20-29', '30-39', '40 or above'])


In [ ]:
df['v212'].value_counts()

v212
20-29          94
<20            35
30-39           4
40 or above     0
Name: count, dtype: int64

In [ ]:
df = df.rename(columns={"v212": "Mother's age at first birth"})

Sex of child

In [ ]:
df['b4'].unique()


array([1, 2])

In [ ]:
df = df.rename(columns={"b4": "sex of child"})

In [ ]:
df['sex of child']=df['sex of child'].replace({1:'Male',2:'Female'})


In [ ]:
df['sex of child'].value_counts()

sex of child
Female    69
Male      64
Name: count, dtype: int64


wealth index

In [ ]:
df['v190a'].value_counts()

v190a
1    34
2    29
4    24
3    23
5    23
Name: count, dtype: int64

In [ ]:
df = df.rename(columns={"v190a": "wealth index"})

In [ ]:
df['wealth index'] = df['wealth index'].replace({1:'Poorest', 2:'Poorer', 3:'Middle', 4:'Richer', 5:'Richest'})



Months of bf

In [ ]:


df = df.rename(columns={'m5': "months of bf"})

In [ ]:
df['months of bf']=pd.cut(df['months of bf'] ,bins=[0,24, 100], right=False , labels=['<24','>24'] , include_lowest=True)



In [ ]:
df['months of bf'].unique()

['<24', '>24']
Categories (2, object): ['<24' < '>24']

In [ ]:
df['months of bf'].value_counts()

months of bf
<24    102
>24     31
Name: count, dtype: int64


Immunization

In [ ]:
df = df.rename(columns={"s370b": "immunization"})

In [ ]:
df['immunization'] = df['immunization'].replace({0: 'Not immunized', 1: 'Immunized'})


In [ ]:
df['immunization'].value_counts()

immunization
Not immunized    126
Immunized          7
Name: count, dtype: int64

Index to birth history

In [ ]:
df = df.rename(columns={"hidx": "index to birth history"})

In [ ]:
df['index to birth history'].value_counts()


index to birth history
1.0    129
2.0      4
Name: count, dtype: int64

Sex of household head

In [ ]:
df = df.rename(columns={"v151": "sex of household head"})

In [ ]:
df['sex of household head'].value_counts()

sex of household head
1    111
2     22
Name: count, dtype: int64

In [ ]:
df['sex of household head']=df['sex of household head'].replace({1:'Male', 2:'Female'})






no of living children

In [ ]:
df = df.rename(columns={"v218": "number of living children"})


In [ ]:
df['number of living children'].value_counts()

number of living children
1    54
2    44
3    24
4     4
6     3
5     2
7     1
8     1
Name: count, dtype: int64

currently in union

In [ ]:
df = df.rename(columns={"s301": "currently in union"})


In [ ]:
df['currently in union'] = df['currently in union'].replace({0:'Never married', 1:'Currently married',2:'Married, gauna not performed',3:'Widowed',4:'Divorced',5:'Separated',6:'Deserted'})



In [ ]:
df['currently in union'].value_counts()

currently in union
Currently married    132
Divorced               1
Name: count, dtype: int64

state

In [ ]:
df = df.rename(columns={"v024": "state"})


In [ ]:
# Create a mapping of state codes to state names
state_code_to_name = {
    1: "Jammu & Kashmir",
    2: "Himachal Pradesh",
    3: "Punjab",
    4: "Chandigarh",
    5: "Uttarakhand",
    6: "Haryana",
    7: "Nct Of Delhi",
    8: "Rajasthan",
    9: "Uttar Pradesh",
    10: "Bihar",
    11: "Sikkim",
    12: "Arunachal Pradesh",
    13: "Nagaland",
    14: "Manipur",
    15: "Mizoram",
    16: "Tripura",
    17: "Meghalaya",
    18: "Assam",
    19: "West Bengal",
    20: "Jharkhand",
    21: "Odisha",
    22: "Chhattisgarh",
    23: "Madhya Pradesh",
    24: "Gujarat",
    25: "Dadra & Nagar Haveli And Daman & Diu",
    27: "Maharashtra",
    28: "Andhra Pradesh",
    29: "Karnataka",
    30: "Goa",
    31: "Lakshadweep",
    32: "Kerala",
    33: "Tamil Nadu",
    34: "Puducherry",
    35: "Andaman & Nicobar Islands",
    36: "Telangana",
    37: "Ladakh"
}

# Create a mapping of state names to regions
state_name_to_region = {
    "Jammu & Kashmir": "North_India",
    "Himachal Pradesh": "North_India",
    "Punjab": "North_India",
    "Chandigarh": "North_India",
    "Uttarakhand": "Central_India",
    "Haryana": "North_India",
    "Nct Of Delhi": "North_India",
    "Rajasthan": "North_India",
    "Uttar Pradesh": "Central_India",
    "Bihar": "East_India",
    "Sikkim": "NorthEast_India",
    "Arunachal Pradesh": "NorthEast_India",
    "Nagaland": "NorthEast_India",
    "Manipur": "NorthEast_India",
    "Mizoram": "NorthEast_India",
    "Tripura": "NorthEast_India",
    "Meghalaya": "NorthEast_India",
    "Assam": "NorthEast_India",
    "West Bengal": "East_India",
    "Jharkhand": "East_India",
    "Odisha": "East_India",
    "Chhattisgarh": "Central_India",
    "Madhya Pradesh": "Central_India",
    "Gujarat": "West_India",
    "Dadra & Nagar Haveli And Daman & Diu": "West_India",
    "Maharashtra": "West_India",
    "Andhra Pradesh": "South_India",
    "Karnataka": "South_India",
    "Goa": "West_India",
    "Lakshadweep": "South_India",
    "Kerala": "South_India",
    "Tamil Nadu": "South_India",
    "Puducherry": "South_India",
    "Andaman & Nicobar Islands": "South_India",
    "Telangana": "South_India",
    "Ladakh": "North_India"
}

# Replace numeric state codes with state names
df['state'] = df['state'].replace(state_code_to_name)

# Replace state names with corresponding regions
df['state'] = df['state'].replace(state_name_to_region)




In [ ]:
df['state'].value_counts()


state
Central_India      40
East_India         36
North_India        21
NorthEast_India    16
South_India        13
West_India          7
Name: count, dtype: int64

mother's weight in kgs(1 decimal)

In [ ]:
df = df.rename(columns={"v437": "mother's weight"})


In [ ]:
import numpy as np
# First, print unique values to see the context
print(df["mother's weight"].unique())

# Update the replacement dictionary to include specific codes
# Update the replacement dictionary to include specific codes
replacement_dict = {
    9994: np.nan,
    9995: np.nan,
    9996: np.nan,
    9999: np.nan
}

# Replace specific codes with NaN in the 'mother's weight' column
df['mother\'s weight'] = df['mother\'s weight'].replace(replacement_dict)

# Drop rows with NaN values in the 'mother's weight' column
df = df.dropna(subset=['mother\'s weight'])

# Print unique values and shape to verify the changes
print(df['mother\'s weight'].unique())
print(f'Shape of df after dropping rows = {df.shape}')

# Print the value counts to check the distribution
print(df['mother\'s weight'].value_counts())


[468. 523. 482. 597. 346. 464. 485. 392. 589. 497. 681. 458. 381. 584.
 367. 614. 579. 395. 496. 437. 512. 500. 549. 382. 489. 420. 413. 404.
 569. 470. 660. 428. 425. 529. 557. 389. 499. 573. 574. 477. 471. 387.
 376. 460. 667. 643. 439. 411. 765. 685. 418. 528. 507. 369. 473. 645.
 429. 364. 446. 481. 441. 352. 493. 679. 525. 445. 402. 433. 635. 592.
 467. 563. 416. 397. 448. 383. 562. 472. 375. 483. 559. 602. 484. 358.
 633. 407. 652. 454. 414. 463. 426. 495. 409. 513. 506. 431. 475. 522.
 601. 558. 536. 455. 593. 649. 476. 452. 603.]
[468. 523. 482. 597. 346. 464. 485. 392. 589. 497. 681. 458. 381. 584.
 367. 614. 579. 395. 496. 437. 512. 500. 549. 382. 489. 420. 413. 404.
 569. 470. 660. 428. 425. 529. 557. 389. 499. 573. 574. 477. 471. 387.
 376. 460. 667. 643. 439. 411. 765. 685. 418. 528. 507. 369. 473. 645.
 429. 364. 446. 481. 441. 352. 493. 679. 525. 445. 402. 433. 635. 592.
 467. 563. 416. 397. 448. 383. 562. 472. 375. 483. 559. 602. 484. 358.
 633. 407. 652. 454. 414. 463.

mother's height

In [ ]:
df = df.rename(columns={"v438": "mother's height"})


In [ ]:
import numpy as np
# First, print unique values to see the context
print(df["mother's height"].unique())

# Update the replacement dictionary to include specific codes
# Update the replacement dictionary to include specific codes
replacement_dict = {
    9994: np.nan,
    9995: np.nan,
    9996: np.nan,
    9999: np.nan
}

# Replace specific codes with NaN in the 'mother's weight' column
df['mother\'s height'] = df['mother\'s height'].replace(replacement_dict)

# Drop rows with NaN values in the 'mother's weight' column
df = df.dropna(subset=['mother\'s height'])

# Print unique values and shape to verify the changes
print(df['mother\'s height'].unique())
print(f'Shape of df after dropping rows = {df.shape}')

# Print the value counts to check the distribution
print(df['mother\'s height'].value_counts())


[1489. 1556. 1552. 1520. 1444. 1522. 1524. 1505. 1645. 1497. 1677. 1573.
 1574. 1311. 1578. 1476. 1586. 1465. 1538. 1475. 1609. 1594. 1392. 1513.
 1511. 1453. 1510. 1491. 1404. 1486. 1519. 1493. 1512. 1507. 1467. 1523.
 1480. 1527. 1496. 1639. 1579. 1521. 1630. 1634. 1532. 1572. 1482. 1563.
 1485. 1464. 1461. 1395. 1449. 1427. 1414. 1484. 1501. 1530. 1626. 1564.
 1434. 1537. 1421. 1555. 1568. 1602. 1571. 1499. 1287. 1435. 1462. 1541.
 1514. 1488. 1342. 1593. 1495. 1416. 1492. 1545. 1504. 1554. 1643. 1517.
 1558. 1412. 1481. 1546. 1557. 1439. 1500. 1526. 1459. 1375. 1415. 1436.
 1543. 1595. 1587. 1539. 1577.]
[1489. 1556. 1552. 1520. 1444. 1522. 1524. 1505. 1645. 1497. 1677. 1573.
 1574. 1311. 1578. 1476. 1586. 1465. 1538. 1475. 1609. 1594. 1392. 1513.
 1511. 1453. 1510. 1491. 1404. 1486. 1519. 1493. 1512. 1507. 1467. 1523.
 1480. 1527. 1496. 1639. 1579. 1521. 1630. 1634. 1532. 1572. 1482. 1563.
 1485. 1464. 1461. 1395. 1449. 1427. 1414. 1484. 1501. 1530. 1626. 1564.
 1434. 1537. 1421. 

mothers bmi (calculated using mothers height and mothers weight)

In [ ]:
import pandas as pd

# Assuming your dataset is stored in a pandas DataFrame called 'df'
# with columns 'mothers_height_cm' and 'mothers_weight_kg'

# Calculate BMI
df['mothers_bmi'] = df['mother\'s weight'] / ((df['mother\'s height'] / 100) ** 2)

# Round BMI to 1 decimal place
df['mothers_bmi'] = df['mothers_bmi'].round(1)




In [ ]:


# Display the shape of the DataFrame
print("Shape of DataFrame:", df.shape)

# Display the value counts of the 'mothers_bmi' column
print("\nValue counts of 'mothers_bmi' column:")
print(df['mothers_bmi'].value_counts())


Shape of DataFrame: (133, 35)

Value counts of 'mothers_bmi' column:
mothers_bmi
2.2    23
2.0    18
1.8    16
2.1    11
2.3    10
1.9    10
1.7    10
2.4     7
2.5     6
2.7     5
2.8     4
2.6     4
1.6     4
3.3     1
1.5     1
2.9     1
3.0     1
1.4     1
Name: count, dtype: int64


In [ ]:


df.shape

(133, 35)

In [ ]:
df

Source of drinking water    hw2 Caste Mother's age at first birth  \
4                    Improved   50.0   OBC                       20-29   
19                   Improved   51.0    SC                       30-39   
27                   Improved   84.0   OBC                       20-29   
47                   Improved   37.0   OBC                       20-29   
76                   Improved   89.0    SC                       20-29   
...                       ...    ...   ...                         ...   
2268                 Improved  112.0    ST                       20-29   
2276                 Improved   96.0   OBC                         <20   
2283               Unimproved   33.0   OBC                       20-29   
2285                 Improved   61.0    SC                         <20   
2310               Unimproved   59.0   OBC                       20-29   

     wealth index  v444a   hw1    v445  mother's height Toilet Facility  ...  \
4          Middle  -98.0   2.0  2111.0           1489.0        Improved  ...   
19        Richest  -91.0   3.0  2160.0           1556.0        Improved  ...   
27         Richer -125.0   8.0  1999.0           1552.0        Improved  ...   
47        Richest   46.0   2.0  2584.0           1520.0        Improved  ...   
76         Poorer -236.0  10.0  1657.0           1444.0        Improved  ...   
...           ...    ...   ...     ...              ...             ...  ...   
2268       Poorer   -5.0  29.0  2570.0           1519.0        Improved  ...   
2276      Poorest   89.0  26.0  2738.0           1539.0     No facility  ...   
2283       Richer -116.0   3.0  1912.0           1577.0         Unknown  ...   
2285       Richer  -97.0   7.0  1998.0           1504.0        Improved  ...   
2310       Middle   87.0   4.0  2772.0           1475.0         Unknown  ...   

                state  index to birth history   Area Religion months of bf  \
4          East_India                     1.0  Urban   Muslim          <24   
19        North_India                     1.0  Urban    Hindu          <24   
27      Central_India                     1.0  Rural    Hindu          <24   
47         East_India                     1.0  Rural    Hindu          <24   
76         East_India                     1.0  Rural    Hindu          <24   
...               ...                     ...    ...      ...          ...   
2268  NorthEast_India                     1.0  Urban   Others          >24   
2276    Central_India                     1.0  Rural    Hindu          <24   
2283      South_India                     1.0  Rural    Hindu          <24   
2285       West_India                     1.0  Urban    Hindu          <24   
2310       East_India                     1.0  Rural    Hindu          <24   

            bmi     H/A   W/A   W/H  mothers_bmi  
4     16.058375  1.2200  20.0  2.45          2.1  
19    15.004899  1.2825  20.5  2.50          2.2  
27    15.298289  1.6775  37.0  4.15          2.0  
47    12.595144  1.1800  13.5  1.80          2.6  
76    18.059918  1.5800  39.5  4.40          1.7  
...         ...     ...   ...   ...          ...  
2268  12.357884  2.2050  51.0  5.55          2.6  
2276   9.429505  2.3475  43.0  4.75          2.7  
2283   6.295595  1.6350  11.5  1.60          1.9  
2285  14.572071  1.4425  25.5  3.00          2.0  
2310  15.250049  1.3800  24.5  2.90          2.8  

[133 rows x 35 columns]

In [ ]:
df = df.rename(columns={"v445": "body mass index"})


child height

In [ ]:
df = df.rename(columns={"hw3": "child's height(in cms)(one decimal)"})


In [ ]:
import numpy as np
# First, print unique values to see the context
print(df["child's height(in cms)(one decimal)"].unique())

# Update the replacement dictionary to include specific codes
# Update the replacement dictionary to include specific codes
replacement_dict = {
    9994: np.nan,
    9995: np.nan,
    9996: np.nan,
    9999: np.nan
}

# Replace specific codes with NaN in the 'mother's weight' column
df['child\'s height(in cms)(one decimal)'] = df['child\'s height(in cms)(one decimal)'].replace(replacement_dict)

# Drop rows with NaN values in the 'mother's weight' column
df = df.dropna(subset=['child\'s height(in cms)(one decimal)'])

# Print unique values and shape to verify the changes
print(df['child\'s height(in cms)(one decimal)'].unique())
print(f'Shape of df after dropping rows = {df.shape}')

# Print the value counts to check the distribution
print(df['child\'s height(in cms)(one decimal)'].value_counts())


[ 558.  583.  741.  542.  702.  867.  875.  752.  814.  871.  721.  784.
  638.  868.  863.  686.  852.  847.  676.  748.  773.  892.  886.  764.
  611.  720.  842.  652.  751.  865.  956.  859.  643.  661.  682.  711.
  573.  740.  816.  683.  648.  850.  762.  732.  813.  719.  920.  754.
  724.  848.  545.  693.  879.  703.  802.  680.  824.  500.  745.  932.
  793.  758.  728.  731.  893.  750.  797.  563.  518.  912.  651.  717.
  722.  845.  798.  792.  710.  982.  897.  725.  851.  804.  821.  642.
  697.  526.  645.  957.  872.  876.  907.  405.  628.  757.  772.  910.
  832.  625.  822.  570.  631.  575.  656.  726.  756.  704.  801.  841.
  594.  695.  800.  952. 1009.  647.  622.]
[ 558.  583.  741.  542.  702.  867.  875.  752.  814.  871.  721.  784.
  638.  868.  863.  686.  852.  847.  676.  748.  773.  892.  886.  764.
  611.  720.  842.  652.  751.  865.  956.  859.  643.  661.  682.  711.
  573.  740.  816.  683.  648.  850.  762.  732.  813.  719.  920.  754.
  724. 

child's weight

In [ ]:
df = df.rename(columns={"hw2": "child's weight(in kgs)(one decimal)"})


In [ ]:
import numpy as np
# First, print unique values to see the context
print(df["child's weight(in kgs)(one decimal)"].unique())

# Update the replacement dictionary to include specific codes
# Update the replacement dictionary to include specific codes
replacement_dict = {
    9994: np.nan,
    9995: np.nan,
    9996: np.nan,
    9999: np.nan
}

# Replace specific codes with NaN in the 'mother's weight' column
df['child\'s weight(in kgs)(one decimal)'] = df['child\'s weight(in kgs)(one decimal)'].replace(replacement_dict)

# Drop rows with NaN values in the 'mother's weight' column
df = df.dropna(subset=['child\'s weight(in kgs)(one decimal)'])

# Print unique values and shape to verify the changes
print(df['child\'s weight(in kgs)(one decimal)'].unique())
print(f'Shape of df after dropping rows = {df.shape}')

# Print the value counts to check the distribution
print(df['child\'s weight(in kgs)(one decimal)'].value_counts())


[ 50.  51.  84.  37.  89. 114. 140.  79. 144. 101. 107.  45.  92. 153.
  73. 148.  81.  88. 104. 118.  91.  62. 106.  61. 120. 100. 109.  59.
  75.  65.  98.  74.  70.  71. 105.  95.  86.  85.  67. 108.  35.  69.
  24.  99.  87. 103.  93.  57. 119.  72.  80.  76. 123.  97.  77. 122.
 115. 134.  68.  66.  32. 157. 135.  31.  83. 102.  96.  55.  78. 111.
 110.  42. 112.  33.]
[ 50.  51.  84.  37.  89. 114. 140.  79. 144. 101. 107.  45.  92. 153.
  73. 148.  81.  88. 104. 118.  91.  62. 106.  61. 120. 100. 109.  59.
  75.  65.  98.  74.  70.  71. 105.  95.  86.  85.  67. 108.  35.  69.
  24.  99.  87. 103.  93.  57. 119.  72.  80.  76. 123.  97.  77. 122.
 115. 134.  68.  66.  32. 157. 135.  31.  83. 102.  96.  55.  78. 111.
 110.  42. 112.  33.]
Shape of df after dropping rows = (133, 35)
child's weight(in kgs)(one decimal)
81.0     5
114.0    5
98.0     4
89.0     4
79.0     4
        ..
148.0    1
57.0     1
119.0    1
153.0    1
33.0     1
Name: count, Length: 74, dtype: int64


In [ ]:
df.to_csv('preprocessed_data1.csv')

In [ ]:
if 'Unnamed: 0' in df.columns:
    df = df.drop('Unnamed: 0', axis=1)
else:
    print("'Unnamed: 0' column not found in DataFrame")


'Unnamed: 0' column not found in DataFrame


In [ ]:
print(df.columns)


Index(['Source of drinking water', 'child's weight(in kgs)(one decimal)',
       'Caste', 'Mother's age at first birth', 'wealth index', 'v444a', 'hw1',
       'body mass index', 'mother's height', 'Toilet Facility', 'v440',
       'number of living children', 'sex of household head',
       'Mother's Occupation', 'Father's Education', 'Father's Occupation',
       'v441', 'hw9', 'sex of child', 'child's height(in cms)(one decimal)',
       'currently in union', 'hw12', 'v442', 'immunization', 'mother's weight',
       'state', 'index to birth history', 'Area', 'Religion', 'months of bf',
       'bmi', 'H/A', 'W/A', 'W/H', 'mothers_bmi'],
      dtype='object')


In [ ]:
# If 'Unnamed: 0' is an index column, you can set the index_col parameter
df = pd.read_csv('/content/preprocessed_data1.csv', index_col=0)


In [ ]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]


In [ ]:
df.describe()

child's weight(in kgs)(one decimal)        v444a         hw1  \
count                           133.000000   133.000000  133.000000   
mean                             87.917293   129.646617   16.195489   
std                              26.303602  1508.297963    9.966199   
min                              24.000000  -350.000000    0.000000   
25%                              71.000000  -164.000000    8.000000   
50%                              89.000000   -95.000000   15.000000   
75%                             105.000000   -27.000000   23.000000   
max                             157.000000  9998.000000   35.000000   

       body mass index  mother's height        v440  \
count       133.000000       133.000000  133.000000   
mean       2120.526316      1510.150376 -212.864662   
std         336.166616        65.390030  109.629872   
min        1410.000000      1287.000000 -587.000000   
25%        1884.000000      1476.000000 -270.000000   
50%        2086.000000      1510.000000 -213.000000   
75%        2299.000000      1552.000000 -143.000000   
max        3348.000000      1677.000000   67.000000   

       number of living children          v441           hw9  \
count                 133.000000    133.000000    133.000000   
mean                    2.052632   9224.714286  12703.150376   
std                     1.292846    399.421069  19099.269724   
min                     1.000000   7862.000000   5608.000000   
25%                     1.000000   9016.000000   7776.000000   
50%                     2.000000   9224.000000   8419.000000   
75%                     3.000000   9480.000000   9455.000000   
max                     8.000000  10244.000000  99998.000000   

       child's height(in cms)(one decimal)          hw12          v442  \
count                           133.000000    133.000000    133.000000   
mean                            753.556391  13401.789474  10824.984962   
std                             113.250019  18937.871455  13665.080806   
min                             405.000000   6698.000000   6001.000000   
25%                             683.000000   8484.000000   7866.000000   
50%                             751.000000   9194.000000   8704.000000   
75%                             847.000000  10165.000000   9613.000000   
max                            1009.000000  99998.000000  99998.000000   

       mother's weight  index to birth history         bmi         H/A  \
count       133.000000              133.000000  133.000000  133.000000   
mean        484.533835                1.030075   15.274177    1.708891   
std          87.396133                0.171440    2.471570    0.283125   
min         346.000000                1.000000    6.295595    0.837500   
25%         418.000000                1.000000   13.961704    1.532500   
50%         471.000000                1.000000   15.250049    1.702500   
75%         529.000000                1.000000   16.585542    1.942500   
max         765.000000                2.000000   21.732700    2.347500   

              W/A         W/H  mothers_bmi  
count  133.000000  133.000000   133.000000  
mean    38.958647    4.345865     2.127068  
std     13.151801    1.315180     0.339815  
min      7.000000    1.150000     1.400000  
25%     30.500000    3.500000     1.900000  
50%     39.500000    4.400000     2.100000  
75%     47.500000    5.200000     2.300000  
max     73.500000    7.800000     3.300000

In [ ]:
import pandas as pd

# Assuming your dataset is in a DataFrame called df
# Let's first look at the data
print(df.describe())

# Dropping the 'Unnamed: 0' column if it exists
if 'Unnamed: 0' in df.columns:
    df = df.drop('Unnamed: 0', axis=1)

# Checking unique values and shapes
print(df['number of living children'].unique())
print(f'shape of original df = {df.shape}')

# Handling 'number of living children' by replacing outliers and dropping them
df["number of living children"] = df["number of living children"].replace({10:999, 11:999, 12:999, 13:999})
indexNames = df[df['number of living children'] == 999].index
df.drop(indexNames , inplace=True)
print(df['number of living children'].unique())
print(f'shape of new df = {df.shape}')

# Checking and cleaning 'index to birth history'
print(df['index to birth history'].unique())
print(f'shape of original df = {df.shape}')
indexNames = df[df['index to birth history'] == 4].index
df.drop(indexNames , inplace=True)
print(df['index to birth history'].unique())
print(f'shape of new df = {df.shape}')

# Now let's take a look at other columns and their unique values
print(df['child\'s weight(in kgs)(one decimal)'].unique())
print(df['body mass index'].unique())
print(df['mother\'s height'].unique())
print(df['child\'s height(in cms)(one decimal)'].unique())
print(df['mother\'s weight'].unique())
print(df['mothers_bmi'].unique())

# If there are outliers or invalid values, we should handle them similarly
# For instance, let's handle 'child\'s weight(in kgs)(one decimal)'
indexNames = df[df['child\'s weight(in kgs)(one decimal)'] > 999].index
df.drop(indexNames , inplace=True)

# Checking unique values again after cleaning
print(df['child\'s weight(in kgs)(one decimal)'].unique())
print(f'shape of final df = {df.shape}')

# Describe the cleaned DataFrame
print(df.describe())


       child's weight(in kgs)(one decimal)        v444a         hw1  \
count                           133.000000   133.000000  133.000000   
mean                             87.917293   129.646617   16.195489   
std                              26.303602  1508.297963    9.966199   
min                              24.000000  -350.000000    0.000000   
25%                              71.000000  -164.000000    8.000000   
50%                              89.000000   -95.000000   15.000000   
75%                             105.000000   -27.000000   23.000000   
max                             157.000000  9998.000000   35.000000   

       body mass index  mother's height        v440  \
count       133.000000       133.000000  133.000000   
mean       2120.526316      1510.150376 -212.864662   
std         336.166616        65.390030  109.629872   
min        1410.000000      1287.000000 -587.000000   
25%        1884.000000      1476.000000 -270.000000   
50%        2086.000000      15

In [ ]:

from sklearn import preprocessing

In [ ]:

dfl = pd.DataFrame()

STATE
AREA
RELIGION
CAASTE
Father's Education
Father's Occupation
Mother's Occupation
Source of drinking water
Toilet Facility
Mother's age at first birth
sex of child
wealth index
months of bf
immunization
sex of household head
currently in union

In [ ]:

df.to_csv('sampled_final_data_preprocessed.csv')


In [ ]:
from google.colab import files
files.download('sampled_final_data_preprocessed.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>